
--------------------------------------------------------
--  DDL for Sequence SEC_USUARIO_ID
--------------------------------------------------------

   CREATE SEQUENCE  "INVATED"."SEC_USUARIO_ID"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_LIBROS_PEDIDO
--------------------------------------------------------

   CREATE SEQUENCE  "INVATED"."SEQ_ID_LIBROS_PEDIDO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table LIBROS
--------------------------------------------------------

  CREATE TABLE "INVATED"."LIBROS" 
   (	"ISBN" VARCHAR2(13 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"CANTIDAD" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIBROS_PEDIDO
--------------------------------------------------------

  CREATE TABLE "INVATED"."LIBROS_PEDIDO" 
   (	"ID_PEDIDO" NUMBER(10,0), 
	"ISBN" VARCHAR2(13 BYTE), 
	"USUARIO_ID" NUMBER(4,0), 
	"CANTIDAD" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "INVATED"."USUARIO" 
   (	"ID_USUARIO" NUMBER(4,0), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"CLAVE" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into INVATED.LIBROS
SET DEFINE OFF;
Insert into INVATED.LIBROS (ISBN,NOMBRE,CANTIDAD) values ('1234567890123','Relatos de un naufrago','11');
Insert into INVATED.LIBROS (ISBN,NOMBRE,CANTIDAD) values ('1231231400bh1','Principito','12');
REM INSERTING into INVATED.LIBROS_PEDIDO
SET DEFINE OFF;
Insert into INVATED.LIBROS_PEDIDO (ID_PEDIDO,ISBN,USUARIO_ID,CANTIDAD) values ('4','1234567890123','54','1');
REM INSERTING into INVATED.USUARIO
SET DEFINE OFF;
Insert into INVATED.USUARIO (ID_USUARIO,USUARIO,CLAVE,FECHA_CREACION) values ('54','chr123','chr123',to_date('12/08/2019','DD/MM/RRRR'));
Insert into INVATED.USUARIO (ID_USUARIO,USUARIO,CLAVE,FECHA_CREACION) values ('52','chris123','123',to_date('12/08/2019','DD/MM/RRRR'));
--------------------------------------------------------
--  DDL for Index PK_ID_PEDIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "INVATED"."PK_ID_PEDIDO" ON "INVATED"."LIBROS_PEDIDO" ("ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "INVATED"."UNIQUE_USER" ON "INVATED"."USUARIO" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Function FUNC_VERIFY_STOCK
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "INVATED"."FUNC_VERIFY_STOCK" (isb in varchar, rented_books in number)
return number is
    v_quantity number;
    v_verify number;
    v_new_quantity number;
begin
    select cantidad into v_quantity from libros where ISB=isbn;



    if v_quantity=0 then
        v_verify:=0;
    else
        if rented_books<=v_quantity then
            v_new_quantity:=v_quantity-rented_books;
            v_verify:=v_new_quantity;


        else
            v_verify:=0;
        end if;
    end if;
return v_verify;
end func_verify_stock;

/
--------------------------------------------------------
--  Constraints for Table LIBROS
--------------------------------------------------------

  ALTER TABLE "INVATED"."LIBROS" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."LIBROS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."LIBROS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."LIBROS" ADD PRIMARY KEY ("ISBN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBROS_PEDIDO
--------------------------------------------------------

  ALTER TABLE "INVATED"."LIBROS_PEDIDO" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."LIBROS_PEDIDO" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."LIBROS_PEDIDO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."LIBROS_PEDIDO" ADD CONSTRAINT "PK_ID_PEDIDO" PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INVATED"."LIBROS_PEDIDO" MODIFY ("ISBN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "INVATED"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."USUARIO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."USUARIO" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."USUARIO" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "INVATED"."USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INVATED"."USUARIO" ADD CONSTRAINT "UNIQUE_USER" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIBROS_PEDIDO
--------------------------------------------------------

  ALTER TABLE "INVATED"."LIBROS_PEDIDO" ADD CONSTRAINT "FK_USUARIO_ID" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "INVATED"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "INVATED"."LIBROS_PEDIDO" ADD CONSTRAINT "FK_ISBN" FOREIGN KEY ("ISBN")
	  REFERENCES "INVATED"."LIBROS" ("ISBN") ENABLE;
